### ISSUE TITLE
Could not find any camera. Returning NULL.

### ISSUE THREAD

**Issue by RobertIndie** [avilapa/vxr#1]
When I ran the example code Planet Editor, it raised errors "[ERROR]: Could not find any camera. Returning NULL".

Information in the console:
```
[INFO]:` Starting application.
[INFO]: Initializing engine systems.
[INFO]: Initialized Render Context with params:
    - max_buffers (100), max_textures (100), max_materials (100), max_framebuffers (100)
[INFO]: Launched rendering thread (VXR_THREADING).
[INFO]: Reached first application loop.
[ERROR]: Could not find any camera. Returning NULL.
```

**Comment by avilapa** [comment]
Yeah I probably shouldn't address this as an error... It happens because the first frame is completed before any cameras are created, and the UI Editor retrieves the main camera each frame... 

I will remove the print on the next update.
