### ISSUE TITLE
nvoglv32.pdb not loaded

### ISSUE THREAD

**Issue by CleverSource** [avilapa/vxr#2]
![image](https://user-images.githubusercontent.com/21996470/54469743-cc3e7580-4772-11e9-9529-5d2feaa511a5.png)

**Comment by avilapa** [comment]
Any more information you can provide on this?

**Comment by CleverSource** [comment]
Happens when attempting to run the examples Mesh and above, anything below 4 works. It's only examples 4 and above. 

I researched it and it usually happens when an invalid pointer is given to OpenGL on AMD Systems.

**Comment by avilapa** [comment]
I was able to reproduce this in one other computer, however it has no AMD in it. I will keep looking into this, thanks for reporting.

**Comment by CleverSource** [comment]
No problem, hopefully you can fix this issue. I can give you a few hardware specifications if you'd want them but mainly I have a 1070 Ti from Zotac. 👍

**Comment by avilapa** [comment]
Hello! Version 0.6.0 should have fixed this issue. It'd be great if you could check this for me, as I do not have appropriate hardware to test it right now... thanks!

**Comment by CleverSource** [comment]
Will test it right now! I do wish you had a premake and/or cmake option to build with other than genie.

**Comment by CleverSource** [comment]
Just tested and the issue is fixed! Awesome job @avilapa.
